In [1]:
import pandas as pd

In [9]:
data = pd.read_csv('/content/insurance.csv')

In [ ]:
1. Count for each categories of ‘region

In [10]:
region_counts = data['region'].value_counts()
print(region_counts)

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [ ]:
2. Find 50 records of highest ‘age’ and export data/table to desktop

In [14]:
import os

In [15]:
home_dir = os.path.expanduser("~")

In [16]:
desktop_path = os.path.join(home_dir, "Desktop")

In [19]:
if not os.path.exists(desktop_path):
    os.makedirs(desktop_path)

In [20]:
file_path = os.path.join(desktop_path, "top_50_ages.csv")
top_50_ages.to_csv(file_path, index=False)

In [ ]:
3. Add index name ‘quick’ on ‘id’

In [22]:
data.set_index('id', inplace=True)
data.index.name = 'quick'

In [ ]:
4. Describe the schema of table

In [23]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1338 entries, 1001 to 2338
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 83.6+ KB
None

In [ ]:
5. Create view name as ‘gender’ where users can not see ‘sex’ [Hint: first run
appropriate query then create view]

In [24]:
gender_view = data.drop(columns=['sex'])

In [ ]:
6. Rename the view as ‘type’

In [25]:
type_view = gender_view

In [ ]:
7. Count how many are ‘northwest’ insurance holders

In [26]:
northwest_count = (data['region'] == 'northwest').sum()
print(f"Number of 'northwest' insurance holders: {northwest_count}")

Number of 'northwest' insurance holders: 325

In [ ]:
8. Count how many insurance holders were ‘femail’

In [27]:
female_count = (data['sex'] == 'female').sum()
print(f"Number of female insurance holders: {female_count}")

Number of female insurance holders: 662

In [ ]:
9. Create Primary key on a suitable column

In [29]:
data.index.is_unique

True

In [ ]:
10. Create a new column ‘ratio’ which is age multiply by bmi

In [30]:
data['ratio'] = data['age'] * data['bmi']

In [ ]:
11. Arrange the table from high to low according to charges

In [31]:
sorted_by_charges = data.sort_values(by='charges', ascending=False)
print(sorted_by_charges.head())

       age     sex     bmi  children smoker     region      charges     ratio
quick
1544    54  female  47.410         0    yes  southeast  63770.42801  2560.140
2301    45    male  30.360         0    yes  southeast  62592.87309  1366.200
2231    52    male  34.485         3    yes  northwest  60021.39897  1793.220
1578    31  female  38.095         1    yes  northeast  58571.07448  1180.945
1820    33  female  35.530         0    yes  northwest  55135.40209  1172.490

In [ ]:
12. Find MAX of ‘charges’

In [32]:
max_charges = data['charges'].max()
print(f"The maximum charges are: {max_charges}")

The maximum charges are: 63770.42801

In [ ]:
13. Find MIN of ‘charges’

In [33]:
min_charges = data['charges'].min()
print(f"The minimum charges are: {min_charges}")

The minimum charges are: 1121.8739

In [ ]:
14. Find average of ‘charges’ of male and female

In [34]:
average_charges = data.groupby('sex')['charges'].mean()
print(average_charges)

sex
female    12569.578844
male      13956.751178
Name: charges, dtype: float64

In [ ]:
15. Write a Query to rename column name sex to Gender

In [37]:
data.rename(columns={'sex': 'Gender'}, inplace=True)

In [ ]:
16. Add new column as HL_Charges where more than average charges should be categorized as HIGH and less than average charges should be categorized as LOW

In [38]:
average_charges = data['charges'].mean()
data['HL_Charges'] = data['charges'].apply(lambda x: 'HIGH' if x > average_charges else 'LOW')

In [ ]:
17. Change location/position of ‘smoker’ and bring before ‘children’

In [39]:
cols = list(data.columns)
smoker_index = cols.index('smoker')
children_index = cols.index('children')
cols.insert(children_index, cols.pop(smoker_index))

In [40]:
data = data[cols]

In [ ]:
18. Show top 20 records

In [41]:
print(data.head(20))

       age  Gender     bmi smoker  children     region      charges     ratio  \
quick
1001    19  female  27.900    yes         0  southwest  16884.92400   530.100
1002    18    male  33.770     no         1  southeast   1725.55230   607.860
1003    28    male  33.000     no         3  southeast   4449.46200   924.000
1004    33    male  22.705     no         0  northwest  21984.47061   749.265
1005    32    male  28.880     no         0  northwest   3866.85520   924.160
1006    31  female  25.740     no         0  southeast   3756.62160   797.940
1007    46  female  33.440     no         1  southeast   8240.58960  1538.240
1008    37  female  27.740     no         3  northwest   7281.50560  1026.380
1009    37    male  29.830     no         2  northeast   6406.41070  1103.710
1010    60  female  25.840     no         0  northwest  28923.13692  1550.400
1011    25    male  26.220     no         0  northeast   2721.32080   655.500
1012    62  female  26.290    yes         0  southeast  27808.72510  1629.980
1013    23    male  34.400     no         0  southwest   1826.84300   791.200
1014    56  female  39.820     no         0  southeast  11090.71780  2229.920
1015    27    male  42.130    yes         0  southeast  39611.75770  1137.510
1016    19    male  24.600     no         1  southwest   1837.23700   467.400
1017    52  female  30.780     no         1  northeast  10797.33620  1600.560
1018    23    male  23.845     no         0  northeast   2395.17155   548.435
1019    56    male  40.300     no         0  southwest  10602.38500  2256.800
1020    30    male  35.300    yes         0  southwest  36837.46700  1059.000

      HL_Charges
quick
1001        HIGH
1002         LOW
1003         LOW
1004        HIGH
1005         LOW
1006         LOW
1007         LOW
1008         LOW
1009         LOW
1010        HIGH
1011         LOW
1012        HIGH
1013         LOW
1014         LOW
1015        HIGH
1016         LOW
1017         LOW
1018         LOW
1019         LOW
1020        HIGH

In [ ]:
19. Show bottom 20 records

In [42]:
print(data.tail(20))

       age  Gender     bmi smoker  children     region      charges     ratio  \
quick
2319    35    male  39.710     no         4  northeast  19496.71917  1389.850
2320    39  female  26.315     no         2  northwest   7201.70085  1026.285
2321    31    male  31.065     no         3  northwest   5425.02335   963.015
2322    62    male  26.695    yes         0  northeast  28101.33305  1655.090
2323    62    male  38.830     no         0  southeast  12981.34570  2407.460
2324    42  female  40.370    yes         2  southeast  43896.37630  1695.540
2325    31    male  25.935     no         1  northwest   4239.89265   803.985
2326    61    male  33.535     no         0  northeast  13143.33665  2045.635
2327    42  female  32.870     no         0  northeast   7050.02130  1380.540
2328    51    male  30.030     no         1  southeast   9377.90470  1531.530
2329    23  female  24.225     no         2  northeast  22395.74424   557.175
2330    52    male  38.600     no         2  southwest  10325.20600  2007.200
2331    57  female  25.740     no         2  southeast  12629.16560  1467.180
2332    23  female  33.400     no         0  southwest  10795.93733   768.200
2333    52  female  44.700     no         3  southwest  11411.68500  2324.400
2334    50    male  30.970     no         3  northwest  10600.54830  1548.500
2335    18  female  31.920     no         0  northeast   2205.98080   574.560
2336    18  female  36.850     no         0  southeast   1629.83350   663.300
2337    21  female  25.800     no         0  southwest   2007.94500   541.800
2338    61  female  29.070    yes         0  northwest  29141.36030  1773.270

      HL_Charges
quick
2319        HIGH
2320         LOW
2321         LOW
2322        HIGH
2323         LOW
2324        HIGH
2325         LOW
2326         LOW
2327         LOW
2328         LOW
2329        HIGH
2330         LOW
2331         LOW
2332         LOW
2333         LOW
2334         LOW
2335         LOW
2336         LOW
2337         LOW
2338        HIGH

In [ ]:
20. Randomly select 20% of records and export to desktop

In [44]:
sample_20_percent = data.sample(frac=0.2)
file_path = os.path.join(desktop_path, "sample_20_percent.csv")
sample_20_percent.to_csv(file_path, index=False)

In [ ]:
21. Remove column ‘ratio’

In [45]:
data.drop(columns=['ratio'], inplace=True)

<ipython-input-45-0ba085871f84>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=['ratio'], inplace=True)

In [ ]:
22. Craete one example of Sub Queries involving ‘bmi’ and ‘sex’ and give explanation in the script itself with remarks by using #

In [46]:
average_bmi = data['bmi'].mean()
high_bmi_females_avg = data[(data['Gender'] == 'female') & (data['bmi'] > average_bmi)]['bmi'].mean()
print(f"Average BMI of high BMI females: {high_bmi_females_avg}")

Average BMI of high BMI females: 35.65857843137255

In [ ]:
23. Create a view called Female_HL_Charges that shows only those data where
HL_Charges is High, Female, Smokers and with 0 children

In [48]:
female_hl_charges_view = data[(data['HL_Charges'] == 'HIGH') & (data['Gender'] == 'female') & (data['smoker'] == 'yes') & (data['children'] == 0)]

In [ ]:
24. Update children column if there is 0 children then make it as Zero Children, if 1 then one_children, if 2 then two_children, if 3 then three_children, if 4 then
four_children if 5 then five_children else print it as More_than_five_children.

In [49]:
data['children'] = data['children'].replace({0: 'Zero Children', 1: 'One Child', 2: 'Two Children', 3: 'Three Children', 4: 'Four Children', 5: 'Five Children'})
data.loc[data['children'].isin(['6', '7', '8', '9']), 'children'] = 'More_than_five_children'

<ipython-input-49-a7c848c89316>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['children'] = data['children'].replace({0: 'Zero Children', 1: 'One Child', 2: 'Two Children', 3: 'Three Children', 4: 'Four Children', 5: 'Five Children'})